// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.dnvriend.data.Event



object EventProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(Seq(
  """CgtFdmVudC5wcm90byJpCg9QQlBlcnNvbkNyZWF0ZWQSHAoJZmlyc3RuYW1lGAEgASgJUglmaXJzdG5hbWUSGgoIbGFzdG5hb
  WUYAiABKAlSCGxhc3RuYW1lEhwKCXRpbWVzdGFtcBgDIAEoA1IJdGltZXN0YW1wIlAKElBCRmlyc3ROYW1lQ2hhbmdlZBIcCglma
  XJzdE5hbWUYASABKAlSCWZpcnN0TmFtZRIcCgl0aW1lc3RhbXAYAyABKANSCXRpbWVzdGFtcCJNChFQQkxhc3ROYW1lQ2hhbmdlZ
  BIaCghsYXN0TmFtZRgBIAEoCVIIbGFzdE5hbWUSHAoJdGltZXN0YW1wGAMgASgDUgl0aW1lc3RhbXBCHAoYY29tLmdpdGh1Yi5kb
  nZyaWVuZC5kYXRhSAFiBnByb3RvMw=="""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}