// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.dnvriend.data.Event



@SerialVersionUID(0L)
final case class PBFirstNameChanged(
    firstName: String = "",
    timestamp: Long = 0L
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[PBFirstNameChanged] with com.trueaccord.lenses.Updatable[PBFirstNameChanged] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (firstName != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, firstName) }
      if (timestamp != 0L) { __size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, timestamp) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = firstName
        if (__v != "") {
          output.writeString(1, __v)
        }
      };
      {
        val __v = timestamp
        if (__v != 0L) {
          output.writeInt64(3, __v)
        }
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.github.dnvriend.data.Event.PBFirstNameChanged = {
      var __firstName = this.firstName
      var __timestamp = this.timestamp
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __firstName = __input.readString()
          case 24 =>
            __timestamp = __input.readInt64()
          case tag => __input.skipField(tag)
        }
      }
      com.github.dnvriend.data.Event.PBFirstNameChanged(
          firstName = __firstName,
          timestamp = __timestamp
      )
    }
    def withFirstName(__v: String): PBFirstNameChanged = copy(firstName = __v)
    def withTimestamp(__v: Long): PBFirstNameChanged = copy(timestamp = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = firstName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = timestamp
          if (__t != 0L) __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.github.dnvriend.data.Event.PBFirstNameChanged
}

object PBFirstNameChanged extends com.trueaccord.scalapb.GeneratedMessageCompanion[PBFirstNameChanged] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[PBFirstNameChanged] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.dnvriend.data.Event.PBFirstNameChanged = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.github.dnvriend.data.Event.PBFirstNameChanged(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), 0L).asInstanceOf[Long]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventProto.descriptor.getMessageTypes.get(1)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.github.dnvriend.data.Event.PBFirstNameChanged(
  )
  implicit class PBFirstNameChangedLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, PBFirstNameChanged]) extends com.trueaccord.lenses.ObjectLens[UpperPB, PBFirstNameChanged](_l) {
    def firstName: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.firstName)((c_, f_) => c_.copy(firstName = f_))
    def timestamp: com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
  }
  final val FIRSTNAME_FIELD_NUMBER = 1
  final val TIMESTAMP_FIELD_NUMBER = 3
}
