// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.dnvriend.data.Event



@SerialVersionUID(0L)
final case class PBLastNameChanged(
    lastName: String = "",
    timestamp: Long = 0L
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[PBLastNameChanged] with com.trueaccord.lenses.Updatable[PBLastNameChanged] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (lastName != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, lastName) }
      if (timestamp != 0L) { __size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, timestamp) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = lastName
        if (__v != "") {
          output.writeString(1, __v)
        }
      };
      {
        val __v = timestamp
        if (__v != 0L) {
          output.writeInt64(3, __v)
        }
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.github.dnvriend.data.Event.PBLastNameChanged = {
      var __lastName = this.lastName
      var __timestamp = this.timestamp
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __lastName = __input.readString()
          case 24 =>
            __timestamp = __input.readInt64()
          case tag => __input.skipField(tag)
        }
      }
      com.github.dnvriend.data.Event.PBLastNameChanged(
          lastName = __lastName,
          timestamp = __timestamp
      )
    }
    def withLastName(__v: String): PBLastNameChanged = copy(lastName = __v)
    def withTimestamp(__v: Long): PBLastNameChanged = copy(timestamp = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = lastName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = timestamp
          if (__t != 0L) __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.github.dnvriend.data.Event.PBLastNameChanged
}

object PBLastNameChanged extends com.trueaccord.scalapb.GeneratedMessageCompanion[PBLastNameChanged] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[PBLastNameChanged] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.github.dnvriend.data.Event.PBLastNameChanged = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.github.dnvriend.data.Event.PBLastNameChanged(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(1), 0L).asInstanceOf[Long]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventProto.descriptor.getMessageTypes.get(2)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.github.dnvriend.data.Event.PBLastNameChanged(
  )
  implicit class PBLastNameChangedLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, PBLastNameChanged]) extends com.trueaccord.lenses.ObjectLens[UpperPB, PBLastNameChanged](_l) {
    def lastName: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.lastName)((c_, f_) => c_.copy(lastName = f_))
    def timestamp: com.trueaccord.lenses.Lens[UpperPB, Long] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
  }
  final val LASTNAME_FIELD_NUMBER = 1
  final val TIMESTAMP_FIELD_NUMBER = 3
}
