// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.github.dnvriend.data.Command



object CommandProto {
  lazy val descriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(
      com.trueaccord.scalapb.Encoding.fromBase64(Seq(
  """Cg1Db21tYW5kLnByb3RvImgKDlBCQ3JlYXRlUGVyc29uEhwKCWZpcnN0bmFtZRgBIAEoCVIJZmlyc3RuYW1lEhoKCGxhc3RuY
  W1lGAIgASgJUghsYXN0bmFtZRIcCgl0aW1lc3RhbXAYAyABKANSCXRpbWVzdGFtcCJPChFQQkNoYW5nZUZpcnN0TmFtZRIcCglma
  XJzdE5hbWUYASABKAlSCWZpcnN0TmFtZRIcCgl0aW1lc3RhbXAYAyABKANSCXRpbWVzdGFtcCJMChBQQkNoYW5nZUxhc3ROYW1lE
  hoKCGxhc3ROYW1lGAEgASgJUghsYXN0TmFtZRIcCgl0aW1lc3RhbXAYAyABKANSCXRpbWVzdGFtcEIcChhjb20uZ2l0aHViLmRud
  nJpZW5kLmRhdGFIAWIGcHJvdG8z"""
      ).mkString))
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    ))
  }
}